version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zebrastore
      - POSTGRES_USER=zebrastore
      - POSTGRES_DB=zebrastore
